services:
  profile-projector:
    image: nginx:alpine
    container_name: profile_projector
    volumes:
      # This points to the internal Portainer folder for your specific stack
      - /data/compose/5:/usr/share/nginx/html:ro
    networks:
      - web_net
    restart: unless-stopped

networks:
  web_net:
    external: true
    name: my-web-suite_web_net