services:
  profile-projector:
    image: nginx:alpine
    container_name: profile_projector
    volumes:
      # Map your local build output to Nginx
      - "C:/Users/ismail/WEB_dev/profile-projector/dist:/usr/share/nginx/html:ro"
    networks:
      - web_net
    restart: unless-stopped

networks:
  web_net:
    external: true
    name: my-web-suite_web_net