services:
  profile-projector:
    image: nginx:alpine
    container_name: profile_projector
    volumes:
      # Use an absolute path inside the Portainer environment for Git stacks
      - .:/usr/share/nginx/html:ro
    networks:
      - web_net
    restart: unless-stopped

networks:
  web_net:
    external: true
    name: my-web-suite_web_net